name = "managermodeweb"

compatibility_date = "2026-08-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "CLUBS"
class_name = "ClubRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClubRoom"]

[observability]
enabled = true
